[environment]
python-version = "{{ cookiecutter.python_version }}"

[rules]
unresolved-import = "warn"
no-matching-overload = "ignore"
unknown-argument = "ignore"
unresolved-attribute = "warn"
invalid-argument-type = "warn"
invalid-assignment = "warn"
